<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_module_implements_alter().
 */
function hooks_tutorial_module_implements_alter(&$implementations, $hook) {
}

/**
 * Implements hook_preprocess_html().
 */
function hooks_tutorial_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_node_news_article().
 */
function hooks_tutorial_preprocess_node_news_article(&$varaibles) {

}

/**
 * Implements hook_form_alter().
 */
function hooks_tutorial_form_alter(Array $form, FormStateInterface $form_state, $form_id) {
  $form_ids = ['node_news_article_form', 'node_news_article_edit_form'];
  if (in_array($form_id, $form_ids)) {
  }

}

/**
 * Implements hook_form_search_block_form_alter().
 */
function hooks_tutorial_form_search_block_form_alter(&$form, FormStateInterface $form_state) {

}

/**
 * Implements hook_form_views_exposed_form_alter().
 */
function hooks_tutorial_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  if (isset($form['#id']) && $form['#id'] == 'views-exposed-form-news-page-1') {
  }
}

/**
 * Implements hook_node_access().
 */
function hooks_tutorial_node_access(NodeInterface $node, $operation, AccountInterface $account) {
  if ($node->bundle() == 'news_article' && $operation == 'view') {

  }
}